<?php

return [
    [
        'name' => 'The Deck',
        'description' => 'An elevated dining space where we serve great food in a scenic atmosphere, perfect for a more refined beach club experience.',
        'position' => [
            [
                'id' => 1,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/highlight1.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
            [
                'id' => 2,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/daybed.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
        ],
    ],
    [
        'name' => 'Deck Side',
        'description' => 'A comfortable, laid-back zone featuring dry daybeds, ideal for those who want to chill, socialize, and enjoy the view without being in the water.',
        'position' => [
            [
                'id' => 3,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/daybed.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
            [
                'id' => 4,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/daybed.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
        ],
    ],
    [
        'name' => 'Pool Side',
        'description' => 'The heart of the action during the day. Surrounded by water and music, this area brings a lively, energetic poolside experience.',
        'position' => [
            [
                'id' => 3,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/daybed.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
            [
                'id' => 4,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/daybed.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
        ],
    ],
    [
        'name' => 'Party Side',
        'description' => 'Front and center to the stage, this is where the energy peaks. The best spot to enjoy live performances, DJs, and unforgettable party moments.',
        'position' => [
            [
                'id' => 3,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/daybed.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
            [
                'id' => 4,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', 'assets/image/daybed.png', 'img:', 'assets/image/daybed.png'],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => 'assets/image/layout.png',
            ],
        ],
    ],
];
