<?php

return [
    [
        'name' => 'Copacabana',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
        'position' => [
            [
                'id' => 1,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' =>  asset('assets/image/layout.png'),
            ],
            [
                'id' => 2,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' => asset('assets/image/layout.png'),
            ],
        ],
    ],
    [
        'name' => 'Surf Side',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
        'position' => [
            [
                'id' => 3,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' =>  asset('assets/image/layout.png'),
            ],
            [
                'id' => 4,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' =>  asset('assets/image/layout.png'),
            ],
        ],
    ],
    [
        'name' => 'Sultan',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
        'position' => [
            [
                'id' => 3,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' =>  asset('assets/image/layout.png'),
            ],
            [
                'id' => 4,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' =>  asset('assets/image/layout.png'),
            ],
        ],
    ],
    [
        'name' => 'Backstage',
        'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
        'position' => [
            [
                'id' => 3,
                'name' => 'Left Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' =>  asset('assets/image/layout.png'),
            ],
            [
                'id' => 4,
                'name' => 'Right Side A',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
                'image' => ['img:', asset('assets/image/daybed.png'), 'img:', asset('assets/image/daybed.png')],
                'checkIn' => '08:00',
                'checkout' => '21:00',
                'Occupancy' => 'maximum 4',
                'type' => 'daybed',
                'benefits' => [
                    'One-time picnic by the beach for 2 persons (min.3 nights stay) (Valid for 14.00-16.00 session)',
                    'One-time flower bath upon arrival',
                    'One-time in-room breakfast',
                    '10% Spa discount on in-room treatments and Spa on the Rocks treatments',
                    '10% Discount on food and beverages including Rock Bar, BALI',
                ],
                'tnc' => [
                    'Package offer requires a minimum 2 nights stay.',
                    'Package rates are subject to 21% government tax and service charges',
                    'Package offer only valid for direct bookings through our website',
                    'Credit card and deposit are required upon arrival to complete the check-in process',
                    'All benefit inclusions are for 2 (two) persons per room',
                    'All reservations are subject to room availability',
                    'This offer cannot be combined with other promotions or discounts',
                ],
                'layoutImage' =>  asset('assets/image/layout.png'),
            ],
        ],
    ],
];
